<?php

use App\Question;
use Illuminate\Database\Seeder;

class AddDataToTableQuestions extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Створюємо питання для прикладу
        $dataArray =[
            [
                'test_id' => 1,
                'text_q' => 'Текст питання №1',
                'description_q' => 'Опис питання №1',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 0,
                'active_q' => 1,
                'order_q' => 0,
                'image_q' => 'images/good_food.jpg'
            ],
            [
                'test_id' => 1,
                'text_q' => 'Текст питання №2',
                'description_q' => 'Опис питання №2',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 1,
                'active_q' => 1,
                'order_q' => 1,
                'image_q' => 'images/good_food.jpg'
            ],
            [
                'test_id' => 1,
                'text_q' => 'Текст питання №3',
                'description_q' => 'Опис питання №3',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 2,
                'image_q' => 'images/good_food.jpg'
            ],
            [
                'test_id' => 2,
                'text_q' => 'Текст питання №1',
                'description_q' => 'Опис питання №1',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 0,
                'active_q' => 1,
                'order_q' => 0,
                'image_q' => 'images/good_food.jpg'
            ],
            [
                'test_id' => 2,
                'text_q' => 'Текст питання №2',
                'description_q' => 'Опис питання №2',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 1,
                'active_q' => 1,
                'order_q' => 1,
                'image_q' => 'images/good_food.jpg'
            ],
            [
                'test_id' => 2,
                'text_q' => 'Текст питання №3',
                'description_q' => 'Опис питання №3',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 2,
                'image_q' => 'images/good_food.jpg'
            ],
            [
                'test_id' => 3,
                'text_q' => 'Текст питання №1',
                'description_q' => 'Опис питання №1',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 0,
                'active_q' => 1,
                'order_q' => 0,
                'image_q' => 'images/good_food.jpg'
            ],
            [
                'test_id' => 3,
                'text_q' => 'Текст питання №2',
                'description_q' => 'Опис питання №2',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 1,
                'active_q' => 1,
                'order_q' => 1,
                'image_q' => 'images/good_food.jpg'
            ],
            [
                'test_id' => 3,
                'text_q' => 'Текст питання №3',
                'description_q' => 'Опис питання №3',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 2,
                'image_q' => 'images/good_food.jpg'
            ],
            [
                'test_id' => 4,
                'text_q' => 'Курс',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 2,
            ],
            [
                'test_id' => 4,
                'text_q' => 'Окружність грудної клітини (см)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 4,
                'text_q' => 'Окружність талії (см)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 4,
                'text_q' => 'Окружність таза (см)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 4,
                'text_q' => 'Окружність правого стегна (см)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 4,
                'text_q' => 'Окружність лівого стегна (см)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 4,
                'text_q' => 'Коло правого біцепса в стані спокою (см)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 4,
                'text_q' => 'Коло лівого біцепса в стані спокою (см)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 4,
                'text_q' => 'Коло правого в стані напруги (см)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 4,
                'text_q' => 'Коло лівого в стані напруги (см)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 4,
                'text_q' => 'Коло правої гомілки (см)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 4,
                'text_q' => 'Коло лівої гомілки (см)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],

//Test #5 anthropometric data of students
            [
                'test_id' => 5,
                'text_q' => 'Зріст (см)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 5,
                'text_q' => 'Вага (кг/г)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 5,
                'text_q' => 'Індекс ваги тіла (індекс Кетле)',
                'description_q' => '',
                'params_q' => '[\'link\' => \'calc\\calc_imt.php\']',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 5,
                'text_q' => 'Ваго-ростовий індекс',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 5,
                'text_q' => 'Силовий індекс(%)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 5,
                'text_q' => 'ЧСС у спокої',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 5,
                'text_q' => 'Артеріальний тиск',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 5,
                'text_q' => 'Сходова проба (уд/хв)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 5,
                'text_q' => 'Проба Руф’є (уд/хв)',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 5,
                'text_q' => 'Затримка дихання (сек) на вдиху',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
            [
                'test_id' => 5,
                'text_q' => 'Затримка дихання (сек) на видиху',
                'description_q' => '',
                'params_q' => '',
                'bal_q' => 1,
                'type_q' => 2,
                'active_q' => 1,
                'order_q' => 3,
            ],
        ];

        foreach ($dataArray as $item) {
            if(!isset($item['image_q'])) $item['image_q']=null;
            Question::insert([
                'test_id' => $item['test_id'],
                'text_q' => $item['text_q'],
                'description_q' => $item['description_q'],
                'params_q' => $item['params_q'],
                'bal_q' => $item['bal_q'],
                'type_q' => $item['type_q'],
                'active_q' => $item['active_q'],
                'order_q' => $item['order_q'],
                'image_q' => $item['image_q'],
            ]);
        }
    }
}
